Neos:
  NeosIo:
    googleAnalyticsTrackingCode: '%env:GOOGLE_ANALYTICS_TRACKING_CODE%'
    crowdApi:
      username: '%env:CROWD_API_USERNAME%'
      password: '%env:CROWD_API_PASSWORD%'

  ContentRepository:
    Search:
      indexAllWorkspaces: true
      elasticSearch:
        indexName: '%env:BEACH_ELASTICSEARCH_INDEX_NAME%'

  GoogleAnalytics:
    authentication:
      applicationName: 'Neos'
      clientId: '%env:GOOGLE_ANALYTICS_CLIENT_ID%'
      clientSecret: '%env:GOOGLE_ANALYTICS_CLIENT_SECRET%'
      developerKey: '%env:GOOGLE_ANALYTICS_CLIENT_DEVELOPER_KEY%'

Flowpack:
  ElasticSearch:
    clients:
      default:
       - host: '%env:BEACH_ELASTICSEARCH_HOSTNAME%'
         port: '%env:BEACH_ELASTICSEARCH_PORT%'
       - host: '%env:BEACH_ELASTICSEARCH_HOSTNAME%'
         port: '%env:BEACH_ELASTICSEARCH_PORT%'
